# Generated by Django 5.0.4 on 2024-04-09 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_developer_remove_game_developer_review_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
